"""empty message

Revision ID: 23457e4e46c3
Revises: ffdb0610b739
Create Date: 2023-05-15 14:34:01.923974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23457e4e46c3'
down_revision = 'ffdb0610b739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jwt_token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jwt_token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jwt_token_blocklist')
    # ### end Alembic commands ###
